# This file was generated by GoReleaser. DO NOT EDIT.
cask "tview" do
  version "0.0.77"

  on_macos do
    on_intel do
      sha256 "d61050734016dfd7c283ccd5c0ed64e3a9022072e2a0131749e3eb1827d7deed"
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v#{version}/tview_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f83b638f1ed7fffd109980ae9f65a3544b2e2adce4dc80d07c20514715b1c239"
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v#{version}/tview_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f0b84ba8c334241ea0df6ec3f2ce3f8191165ac6decfd8c41028bf430c50f432"
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v#{version}/tview_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4d7ed826af2b74973ecc98adb4896f11867754c2e10bd71d2ae0957b1ddc0a8d"
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v#{version}/tview_linux_arm64.tar.gz"
    end
  end

  name "tview"
  desc "Terminal candlestick chart viewer powered by Bybit market data."
  homepage "https://github.com/devlopersabbir/tview-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tview"

  preflight do
    bin_path = "#{HOMEBREW_PREFIX}/bin/tview"
    FileUtils.rm_f bin_path if File.exist?(bin_path) || File.symlink?(bin_path)
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-d", "com.apple.quarantine", "#{staged_path}/tview"],
                   sudo: false,
                   must_succeed: false
    system_command "/usr/bin/xattr",
                   args: ["-d", "com.apple.provenance", "#{staged_path}/tview"],
                   sudo: false,
                   must_succeed: false
  end

  # No zap stanza required

  caveats <<~EOS
    tview was installed to:
      #{HOMEBREW_PREFIX}/bin/tview

    If your shell cannot find tview, make sure Homebrew's bin directory is in your PATH:
      eval "$(/opt/homebrew/bin/brew shellenv)"   # Apple Silicon
      eval "$(/usr/local/bin/brew shellenv)"      # Intel Mac

    The macOS binary is not Apple-notarized yet. If Gatekeeper blocks it, run:
      xattr -d com.apple.quarantine #{HOMEBREW_PREFIX}/bin/tview 2>/dev/null || true
      xattr -d com.apple.provenance #{HOMEBREW_PREFIX}/bin/tview 2>/dev/null || true
  EOS
end
