# This file was generated by GoReleaser. DO NOT EDIT.
cask "tview" do
  version "0.0.8"

  on_macos do
    on_intel do
      sha256 "8d6301ccd1c26d3f9931861d681e5f68e1c20e47c742523f3a46902fd29f2522"
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v#{version}/tview_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6e9c16b4df44fb84fd1d795f99262de21be6de50ebaf02b2f58a41ae3ea3eb82"
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v#{version}/tview_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c3ca0795be22d05b2415bf9f8911e8bd11ef5f4267cff89612652d421f6eca0a"
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v#{version}/tview_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1890b5aa13d65d64632c120ac9014b9ca58ac2dc750dd3655bb0bbd891729072"
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v#{version}/tview_linux_arm64.tar.gz"
    end
  end

  name "tview"
  desc "Terminal candlestick chart viewer powered by Bybit market data."
  homepage "https://github.com/devlopersabbir/tview-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tview"

  # No zap stanza required

end
