# This file was generated by GoReleaser. DO NOT EDIT.
cask "tview" do
  version "0.0.69"

  on_macos do
    on_intel do
      sha256 "3f1bee58b786fc3420692e97be225a5eee7c5931bf5a208118895d3aec2e1759"
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v#{version}/tview_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "86661bbb85f8c57ee1bee0d3cf6a5e7f483ca25dd24612d7b012629abd9cf75a"
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v#{version}/tview_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "db1053d3a472bf2958864e591b74b2a5f151e07e4aa6838fd03debc225baf23e"
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v#{version}/tview_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7040cf7b1f82eca0e67b13bbcc978ae1cc3cb0151361bb9874a995b77a3cf75c"
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v#{version}/tview_linux_arm64.tar.gz"
    end
  end

  name "tview"
  desc "Terminal candlestick chart viewer powered by Bybit market data."
  homepage "https://github.com/devlopersabbir/tview-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tview"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-d", "com.apple.quarantine", "#{staged_path}/tview"],
                   sudo: false,
                   must_succeed: false
    system_command "/usr/bin/xattr",
                   args: ["-d", "com.apple.provenance", "#{staged_path}/tview"],
                   sudo: false,
                   must_succeed: false
  end

  # No zap stanza required

  caveats <<~EOS
    tview was installed to:
      #{HOMEBREW_PREFIX}/bin/tview

    If your shell cannot find tview, make sure Homebrew's bin directory is in your PATH:
      eval "$(/opt/homebrew/bin/brew shellenv)"   # Apple Silicon
      eval "$(/usr/local/bin/brew shellenv)"      # Intel Mac

    The macOS binary is not Apple-notarized yet. If Gatekeeper blocks it, run:
      xattr -d com.apple.quarantine #{HOMEBREW_PREFIX}/bin/tview 2>/dev/null || true
      xattr -d com.apple.provenance #{HOMEBREW_PREFIX}/bin/tview 2>/dev/null || true
  EOS
end
