# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tview < Formula
  desc "Terminal candlestick chart viewer powered by Bybit market data."
  homepage "https://github.com/devlopersabbir/tview-cli"
  version "0.0.63"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v0.0.63/tview_darwin_amd64.tar.gz"
      sha256 "e16e019196d16f4163aca6a083b382ef2031731739eeabe6ee8b4be22e203632"

      define_method(:install) do
        bin.install "tview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v0.0.63/tview_darwin_arm64.tar.gz"
      sha256 "1167cfaf6f581992b97dcecd678663f8a9840c7bd75a5d5c7296bd66cf02bad4"

      define_method(:install) do
        bin.install "tview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v0.0.63/tview_linux_amd64.tar.gz"
      sha256 "4a5e6ddaa5f7ab0708305e2c09a1c03520111c1477c9d0619056101c43cda74d"
      define_method(:install) do
        bin.install "tview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v0.0.63/tview_linux_arm64.tar.gz"
      sha256 "f7656c945f85958f8a81537916b2dda2ef54a08924ec519f444a870051fa654a"
      define_method(:install) do
        bin.install "tview"
      end
    end
  end

  def post_install
    quiet_system "xattr", "-d", "com.apple.quarantine", "#{bin}/tview" if OS.mac?
    quiet_system "xattr", "-d", "com.apple.provenance", "#{bin}/tview" if OS.mac?
  end

  def caveats
    <<~EOS
      The macOS binary is not Apple-notarized yet. If Gatekeeper blocks it, run:
        xattr -d com.apple.quarantine #{bin}/tview 2>/dev/null || true
        xattr -d com.apple.provenance #{bin}/tview 2>/dev/null || true
    EOS
  end

  test do
    system "#{bin}/tview", "version"
  end
end
