# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tview < Formula
  desc "Terminal candlestick chart viewer powered by Bybit market data."
  homepage "https://github.com/devlopersabbir/tview-cli"
  version "0.0.62"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v0.0.62/tview_darwin_amd64.tar.gz"
      sha256 "e16b7f16b9933d5cab645a1a0f02f4dc3bb5738a481d352c75fd4933580a3fe4"

      define_method(:install) do
        bin.install "tview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v0.0.62/tview_darwin_arm64.tar.gz"
      sha256 "293c8b88208f7c97d4700f5e6b023b7072064b20b4226b3927e12025160a480b"

      define_method(:install) do
        bin.install "tview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v0.0.62/tview_linux_amd64.tar.gz"
      sha256 "6f17df71e125761782626c222e240a7ed7a4033b180906f5715a2837f64b47b7"
      define_method(:install) do
        bin.install "tview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v0.0.62/tview_linux_arm64.tar.gz"
      sha256 "8a58e35a3914268070cb492fa517cb7a26d4cdbdbbeb38e8639a7c9f08e279f5"
      define_method(:install) do
        bin.install "tview"
      end
    end
  end

  def post_install
    quiet_system "xattr", "-d", "com.apple.quarantine", "#{bin}/tview" if OS.mac?
    quiet_system "xattr", "-d", "com.apple.provenance", "#{bin}/tview" if OS.mac?
  end

  def caveats
    <<~EOS
      The macOS binary is not Apple-notarized yet. If Gatekeeper blocks it, run:
        xattr -d com.apple.quarantine #{bin}/tview 2>/dev/null || true
        xattr -d com.apple.provenance #{bin}/tview 2>/dev/null || true
    EOS
  end

  test do
    system "#{bin}/tview", "version"
  end
end
