# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tview < Formula
  desc "Terminal candlestick chart viewer powered by Bybit market data."
  homepage "https://github.com/devlopersabbir/tview-cli"
  version "0.0.52"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v0.0.52/tview_darwin_amd64.tar.gz"
      sha256 "25108a2da29b9185a183674190f982fdf56f3639c1fe02d76dc05b0de87c507d"

      define_method(:install) do
        bin.install "tview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v0.0.52/tview_darwin_arm64.tar.gz"
      sha256 "3a83220e9261d37318b040f7ef1b92061100648d0e6c5bedfa82368848f2a991"

      define_method(:install) do
        bin.install "tview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v0.0.52/tview_linux_amd64.tar.gz"
      sha256 "dcbfefa1b0520a0014700101149812d6f1822ceb78946d413f019fdb76e53d43"
      define_method(:install) do
        bin.install "tview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devlopersabbir/tview-cli/releases/download/v0.0.52/tview_linux_arm64.tar.gz"
      sha256 "a309e616dc692211f0eb463e31a5905c7cd3ba0505fdf5dc30e449a9da94faac"
      define_method(:install) do
        bin.install "tview"
      end
    end
  end

  def post_install
    quiet_system "xattr", "-d", "com.apple.quarantine", "#{bin}/tview" if OS.mac?
    quiet_system "xattr", "-d", "com.apple.provenance", "#{bin}/tview" if OS.mac?
  end

  def caveats
    <<~EOS
      The macOS binary is not Apple-notarized yet. If Gatekeeper blocks it, run:
        xattr -d com.apple.quarantine #{bin}/tview 2>/dev/null || true
        xattr -d com.apple.provenance #{bin}/tview 2>/dev/null || true
    EOS
  end

  test do
    system "#{bin}/tview", "version"
  end
end
